---
- name: Install Wendy CLI with Homebrew when selected
  community.general.homebrew:
    name: wendylabsinc/tap/wendy
    state: present
    path: "{{ homebrew_prefix }}/bin"
  when: install_wendy_cli

- name: Install Wendy macOS daemon app with Homebrew Cask when selected
  community.general.homebrew_cask:
    name: wendylabsinc/tap/wendy-agent
    state: present
    path: "{{ homebrew_prefix }}/bin"
  when: install_wendy_daemon
