//go:build windows

package winusb

// Driver package (INF) generation. The INF binds inbox winusb.sys to the Jetson
// device IDs and exposes a stable device interface GUID so wendy can open the
// device by interface (SetupDiGetClassDevs with DIGCF_DEVICEINTERFACE).

import (
	"fmt"
	"strings"

	"github.com/wendylabsinc/wendy/go/internal/cli/tegraflash/rcm"
)

// DeviceInterfaceGUID is wendy's stable WinUSB device-interface GUID for Jetson
// devices. The transport opens devices exposing this interface. Fixed forever.
const DeviceInterfaceGUID = "{9F5D2C3A-7B14-4E8D-9C6F-1A2B3C4D5E6F}"

// catalogFileName / infFileName are the package file names (co-located when staged).
const (
	catalogFileName = "wendy_jetson.cat"
	infFileName     = "wendy_jetson.inf"
)

// jetsonModels are the device IDs the package binds WinUSB to — every RCM
// recovery PID (Thor plus each T234 module SKU) and the initrd-flash ADB
// gadget — with their INF model descriptions. Pre-staging all of them means
// the gadget binds automatically when it enumerates mid-flash, with no second
// prompt. The T234 mass-storage gadget (1d6b:0104) is deliberately absent: it
// must bind the inbox usbstor/disk stack, not WinUSB.
func jetsonModels() []struct{ desc, id string } {
	hwid := func(pid uint16) string {
		return fmt.Sprintf("USB\\VID_%04X&PID_%04X", VendorNVIDIA, pid)
	}
	models := []struct{ desc, id string }{
		{"NVIDIA Jetson AGX Thor (recovery)", hwid(ProductThor)},
	}
	for _, pid := range []uint16{
		rcm.ProductOrinAGX32, rcm.ProductOrinAGX64,
		rcm.ProductOrinNX16, rcm.ProductOrinNX8,
		rcm.ProductOrinNano8, rcm.ProductOrinNano4,
	} {
		name, _ := rcm.T234ModuleName(pid)
		models = append(models, struct{ desc, id string }{"NVIDIA Jetson " + name + " (recovery)", hwid(pid)})
	}
	return append(models, struct{ desc, id string }{"NVIDIA Jetson flashing gadget", hwid(ProductGadget)})
}

// jetsonHardwareIDs are the bare device IDs from jetsonModels, for binding.
func jetsonHardwareIDs() []string {
	models := jetsonModels()
	ids := make([]string, 0, len(models))
	for _, m := range models {
		ids = append(ids, m.id)
	}
	return ids
}

// generateINF returns the WinUSB INF text binding the Jetson hardware IDs.
func generateINF() string {
	// Per-model device lines shared by both arch sections.
	models := jetsonModels()
	var devLines strings.Builder
	for i, m := range models {
		fmt.Fprintf(&devLines, "%%Dev%d.desc%% = USB_Install, %s\n", i, m.id)
	}
	var strLines strings.Builder
	for i, m := range models {
		fmt.Fprintf(&strLines, "Dev%d.desc = \"%s\"\n", i, m.desc)
	}

	// DriverVer date is fixed and in the past so PnP always prefers a device's
	// existing better driver if any, and never rejects ours as future-dated.
	// The version was bumped to 1.1.0.0 when the T234 module PIDs were added,
	// so hosts with the Thor-era 1.0.0.0 package staged rank this one higher
	// for the IDs both packages cover.
	return fmt.Sprintf(`; Wendy Labs — WinUSB binding for NVIDIA Jetson USB flashing.
; Generated by wendy; binds inbox winusb.sys to Jetson recovery + gadget IDs.
[Version]
Signature   = "$WINDOWS NT$"
Class       = USBDevice
ClassGuid   = {88BAE032-5A81-49F0-BC3D-A4FF138216D6}
Provider    = %%ProviderName%%
CatalogFile = %s
DriverVer   = 01/01/2026,1.1.0.0
PnpLockdown = 1

[Manufacturer]
%%ProviderName%% = Standard,NTamd64,NTarm64

[Standard.NTamd64]
%s
[Standard.NTarm64]
%s
[USB_Install]
Include = winusb.inf
Needs   = WINUSB.NT

[USB_Install.Services]
Include = winusb.inf
Needs   = WINUSB.NT.Services

[USB_Install.HW]
AddReg = Dev_AddReg

[Dev_AddReg]
HKR,,DeviceInterfaceGUIDs,0x00010000,"%s"

[Strings]
ProviderName = "Wendy Labs"
%s`,
		catalogFileName,
		devLines.String(),
		devLines.String(),
		DeviceInterfaceGUID,
		strLines.String(),
	)
}
