version: 2
updates:
  - package-ecosystem: gomod
    directory: /go
    schedule:
      interval: weekly
      day: monday

  - package-ecosystem: npm
    directory: /screencast
    schedule:
      interval: weekly
      day: monday

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
