#!/bin/sh

# Run swift format on the Sources directory
echo "Running Swift format..."
swift format --recursive --in-place Sources/

# Add formatted files back to the commit
git add Sources/

# If swift format fails, prevent the commit
if [ $? -ne 0 ]; then
  echo "Swift format failed. Commit aborted."
  exit 1
fi 