---
- name: Run common info
  ansible.builtin.include_tasks:
    file: info.yml
    apply:
      tags: info
  tags: [info]

- name: Include macOS common tasks
  ansible.builtin.include_tasks:
    file: macos.yml
    apply:
      tags: [common, ssh, git]
  when: ansible_facts.system == 'Darwin'
  tags: [common, ssh, git]

- name: Include Ubuntu common tasks
  ansible.builtin.include_tasks:
    file: ubuntu.yml
    apply:
      tags: [common, ssh, git]
  when: ansible_facts.distribution == 'Ubuntu'
  tags: [common, ssh, git]

- name: Include Windows common tasks
  ansible.builtin.include_tasks:
    file: windows.yml
    apply:
      tags: [common, ssh, git]
  when: ansible_facts.os_family == 'Windows'
  tags: [common, ssh, git]
