---
- name: Run common preflight
  ansible.builtin.include_tasks:
    file: preflight.yml
    apply:
      tags: preflight
  tags: [always]

- name: Include macOS common tasks
  ansible.builtin.include_tasks: macos.yml
  when: ansible_facts.system == 'Darwin'
  tags: [common, ssh, git]

- name: Include Ubuntu common tasks
  ansible.builtin.include_tasks: ubuntu.yml
  when: ansible_facts.distribution == 'Ubuntu'
  tags: [common, ssh, git]

- name: Include Windows common tasks
  ansible.builtin.include_tasks: windows.yml
  when: ansible_facts.os_family == 'Windows'
  tags: [common, ssh, git]
