---
- name: Run Swift preflight
  ansible.builtin.include_tasks:
    file: preflight.yml
    apply:
      tags: preflight
  tags: [always]

- name: Include macOS Swift tasks
  ansible.builtin.include_tasks: macos.yml
  when: ansible_facts.system == 'Darwin'
  tags: [swift]

- name: Include Ubuntu Swift tasks
  ansible.builtin.include_tasks: ubuntu.yml
  when: ansible_facts.distribution == 'Ubuntu'
  tags: [swift]

- name: Include Windows Swift tasks
  ansible.builtin.include_tasks: windows.yml
  when: ansible_facts.os_family == 'Windows'
  tags: [swift]
