---
- name: Run Swift preflight
  ansible.builtin.include_tasks:
    file: preflight.yml
    apply:
      tags: preflight
  tags: [preflight]

- name: Include macOS Swift tasks
  ansible.builtin.include_tasks:
    file: macos.yml
    apply:
      tags: [swift]
  when: ansible_facts.system == 'Darwin'
  tags: [swift]

- name: Include Ubuntu Swift tasks
  ansible.builtin.include_tasks:
    file: ubuntu.yml
    apply:
      tags: [swift]
  when: ansible_facts.distribution == 'Ubuntu'
  tags: [swift]

- name: Include Windows Swift tasks
  ansible.builtin.include_tasks:
    file: windows.yml
    apply:
      tags: [swift]
  when: ansible_facts.os_family == 'Windows'
  tags: [swift]
