// bundle extracts files from a tegraflash tarball produced by the WendyOS CI.
// The applet binaries inside the tarball are NVIDIA proprietary — this package
// never embeds them; it extracts them at runtime from the user's own bundle,
// which they obtained under NVIDIA's Jetson Software License Agreement.
package bundle

import (
	"archive/tar"
	"compress/gzip"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

// Bundle provides access to files inside a tegraflash tarball.
type Bundle struct {
	path string
}

// Open opens the bundle at the given path (must be a .tar.gz or .tar file).
func Open(path string) (*Bundle, error) {
	if _, err := os.Stat(path); err != nil {
		return nil, fmt.Errorf("bundle not found at %s: %w", path, err)
	}
	return &Bundle{path: path}, nil
}

// Close is a no-op; bundles are read on demand.
func (b *Bundle) Close() error { return nil }

// Applet returns the contents and filename of the recovery applet binary.
// Tries T264 (Thor) first, then T234 (Orin) as fallback.
func (b *Bundle) Applet() ([]byte, string, error) {
	for _, name := range []string{"applet_t264.bin", "applet_t234.bin"} {
		data, err := b.extract(name)
		if err == nil {
			return data, name, nil
		}
	}
	return nil, "", fmt.Errorf("applet binary not found in bundle (tried applet_t264.bin, applet_t234.bin)")
}

// MB1Bin returns the T264 MB1 bootloader binary.
// Tries the aligned+signed variant (from rcmboot_blob) first, then falls back
// to the raw binary present in standard L4T bundles.
func (b *Bundle) MB1Bin() ([]byte, error) {
	for _, name := range []string{"mb1_t264_prod_aligned_sigheader.bin.encrypt", "mb1_t264_prod.bin"} {
		if data, err := b.extract(name); err == nil {
			return data, nil
		}
	}
	return nil, fmt.Errorf("mb1 binary not found in bundle")
}

// PSCBL1Bin returns the T264 PSC BL1 binary.
// Tries the aligned+signed variant (from rcmboot_blob) first, then raw binary.
func (b *Bundle) PSCBL1Bin() ([]byte, error) {
	for _, name := range []string{"psc_bl1_t264_prod_aligned_sigheader.bin.encrypt", "psc_bl1_t264_prod.bin"} {
		if data, err := b.extract(name); err == nil {
			return data, nil
		}
	}
	return nil, fmt.Errorf("psc_bl1 binary not found in bundle")
}

// BRBct returns the pre-compiled T264 boot ROM BCT.
// The file is generated by tegrabct_v2 and must be present in the bundle.
func (b *Bundle) BRBct() ([]byte, error) {
	for _, name := range []string{"br_bct_BR.bct", "br_bct.cfg_BR.bct"} {
		if data, err := b.extract(name); err == nil {
			return data, nil
		}
	}
	return nil, fmt.Errorf("BR BCT not found in bundle")
}

// MB1Bct returns the pre-compiled T264 MB1 BCT.
func (b *Bundle) MB1Bct() ([]byte, error) {
	for _, name := range []string{"mb1_bct_MB1_sigheader.bct.encrypt", "mb1_bct.cfg_MB1.bct"} {
		if data, err := b.extract(name); err == nil {
			return data, nil
		}
	}
	return nil, fmt.Errorf("MB1 BCT not found in bundle")
}

// MemBct returns the pre-compiled T264 memory BCT for the given RAMCODE group.
// ramGroup is RAMCODE/2 (e.g. RAMCODE=12 → ramGroup=6 → membct_6_sigheader.bct.encrypt).
// ramGroup=-1 tries the default/first available membct.
func (b *Bundle) MemBct(ramGroup int) ([]byte, error) {
	var candidates []string
	if ramGroup >= 0 {
		candidates = append(candidates, fmt.Sprintf("membct_%d_sigheader.bct.encrypt", ramGroup))
	}
	// Legacy and fallback names.
	for i := 0; i <= 7; i++ {
		candidates = append(candidates, fmt.Sprintf("membct_%d_sigheader.bct.encrypt", i))
	}
	candidates = append(candidates, "mem_bct_rcm.bct", "mem_bct.bct", "membct_rcm.bct")
	for _, name := range candidates {
		if data, err := b.extract(name); err == nil {
			return data, nil
		}
	}
	return nil, fmt.Errorf("memory BCT not found in bundle")
}

// Blob returns the pre-compiled T264 firmware blob sent in Phase 2.
func (b *Bundle) Blob() ([]byte, error) {
	return b.extract("blob.bin")
}

// T264Ready reports whether the bundle contains all files needed for a
// T264 flash (pre-compiled BCTs and blob). When false, BCTs must
// be generated by running the bundle generation tooling first.
func (b *Bundle) T264Ready() bool {
	if _, err := b.BRBct(); err != nil {
		return false
	}
	if _, err := b.MB1Bct(); err != nil {
		return false
	}
	if _, err := b.Blob(); err != nil {
		return false
	}
	return true
}

// RAMGroup returns the memory BCT group index derived from the board's RAMCODE.
// The group is RAMCODE/2 — e.g. RAMCODE 12 → group 6 → membct_6_sigheader.bct.encrypt.
// Returns -1 if the RAMCODE cannot be determined from the bundle.
func (b *Bundle) RAMGroup() int {
	data, err := b.extract("flashvars")
	if err != nil {
		return -1
	}
	for _, line := range strings.Split(string(data), "\n") {
		line = strings.TrimSpace(line)
		if !strings.HasPrefix(line, "RAMCODE=") {
			continue
		}
		val := strings.TrimPrefix(line, "RAMCODE=")
		val = strings.Trim(val, `"'`)
		n, err := strconv.Atoi(val)
		if err != nil {
			return -1
		}
		return n / 2
	}
	return -1
}

// ExtractFile extracts a file by basename from the bundle.
func (b *Bundle) ExtractFile(name string) ([]byte, error) {
	return b.extract(strings.TrimSpace(name))
}

// FindXML returns the contents and filename of the partition layout XML.
// fullEMMC selects the full eMMC layout; false selects recovery/QSPI boot only.
func (b *Bundle) FindXML(fullEMMC bool) ([]byte, string, error) {
	var candidates []string
	if fullEMMC {
		// Full eMMC flash: write all partitions.
		candidates = []string{
			"flash.xml.in",
			"flash_t234_qspi_sdmmc.xml",
			"flash_l4t_t234_sdmmc.xml",
			"flash_t234.xml",
		}
	} else {
		// Recovery / QSPI-only boot firmware update.
		candidates = []string{
			"rcmboot-flash.xml.in",
			"flash_t234_qspi.xml",
			"flash_l4t_t234_nvme.xml",
		}
	}
	for _, name := range candidates {
		data, err := b.extract(name)
		if err == nil {
			return data, name, nil
		}
	}

	// Fall back: find any .xml or .xml.in file in the bundle that looks like a partition layout.
	files, err := b.ListFiles()
	if err != nil {
		return nil, "", fmt.Errorf("no partition layout XML found in bundle")
	}
	for _, f := range files {
		base := filepath.Base(f)
		if (strings.HasSuffix(base, ".xml") || strings.HasSuffix(base, ".xml.in")) && strings.Contains(base, "flash") {
			data, err := b.extract(base)
			if err == nil {
				return data, base, nil
			}
		}
	}

	return nil, "", fmt.Errorf("no partition layout XML found in bundle — expected flash_t234_*.xml")
}

// openTar opens the bundle file and returns a tar.Reader. It detects gzip by
// reading the first two magic bytes rather than relying on the file extension,
// since CI sometimes produces plain-tar bundles with a .tar.gz suffix.
// The caller must close f when done.
func (b *Bundle) openTar() (*tar.Reader, *os.File, func(), error) {
	f, err := os.Open(b.path)
	if err != nil {
		return nil, nil, nil, err
	}

	magic := make([]byte, 2)
	if _, err := io.ReadFull(f, magic); err != nil {
		f.Close()
		return nil, nil, nil, fmt.Errorf("reading archive header: %w", err)
	}
	if _, err := f.Seek(0, io.SeekStart); err != nil {
		f.Close()
		return nil, nil, nil, fmt.Errorf("seeking archive: %w", err)
	}

	isGzip := magic[0] == 0x1f && magic[1] == 0x8b
	if isGzip {
		gr, err := gzip.NewReader(f)
		if err != nil {
			f.Close()
			return nil, nil, nil, fmt.Errorf("opening gzip stream: %w", err)
		}
		return tar.NewReader(gr), f, func() { gr.Close(); f.Close() }, nil
	}
	return tar.NewReader(f), f, func() { f.Close() }, nil
}

// isDir reports whether the bundle path is a directory (extracted bundle).
func (b *Bundle) isDir() bool {
	info, err := os.Stat(b.path)
	return err == nil && info.IsDir()
}

// extract reads the first file matching name (basename only) from the bundle.
// Supports both tar/tar.gz archives and extracted directories.
func (b *Bundle) extract(name string) ([]byte, error) {
	if b.isDir() {
		// Walk the directory tree for the matching basename.
		var result []byte
		err := filepath.WalkDir(b.path, func(path string, d os.DirEntry, err error) error {
			if err != nil || d.IsDir() || result != nil {
				return err
			}
			if filepath.Base(path) == name {
				result, err = os.ReadFile(path)
				return err
			}
			return nil
		})
		if err != nil {
			return nil, err
		}
		if result != nil {
			return result, nil
		}
		return nil, fmt.Errorf("%s not found in bundle %s", name, filepath.Base(b.path))
	}

	tr, _, cleanup, err := b.openTar()
	if err != nil {
		return nil, err
	}
	defer cleanup()

	for {
		hdr, err := tr.Next()
		if err == io.EOF {
			break
		}
		if err != nil {
			return nil, fmt.Errorf("reading archive: %w", err)
		}
		if filepath.Base(hdr.Name) == name {
			return io.ReadAll(tr)
		}
	}

	return nil, fmt.Errorf("%s not found in bundle %s", name, filepath.Base(b.path))
}

// ListFiles returns the names of all files in the bundle (for debugging).
func (b *Bundle) ListFiles() ([]string, error) {
	if b.isDir() {
		var names []string
		err := filepath.WalkDir(b.path, func(path string, d os.DirEntry, err error) error {
			if err != nil || d.IsDir() {
				return err
			}
			rel, _ := filepath.Rel(b.path, path)
			names = append(names, rel)
			return nil
		})
		return names, err
	}

	tr, _, cleanup, err := b.openTar()
	if err != nil {
		return nil, err
	}
	defer cleanup()

	var names []string
	for {
		hdr, err := tr.Next()
		if err == io.EOF {
			break
		}
		if err != nil {
			return nil, err
		}
		names = append(names, hdr.Name)
	}
	return names, nil
}
