//
//Copyright The containerd Authors.
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the gRPC Swift generator plugin for the protocol buffer compiler.
// Source: github.com/containerd/containerd/api/services/introspection/v1/introspection.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/grpc/grpc-swift

import GRPCCore
import GRPCProtobuf
import SwiftProtobuf

// MARK: - containerd.services.introspection.v1.Introspection

/// Namespace containing generated types for the "containerd.services.introspection.v1.Introspection" service.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
public enum Containerd_Services_Introspection_V1_Introspection {
    /// Service descriptor for the "containerd.services.introspection.v1.Introspection" service.
    public static let descriptor = GRPCCore.ServiceDescriptor(fullyQualifiedService: "containerd.services.introspection.v1.Introspection")
    /// Namespace for method metadata.
    public enum Method {
        /// Namespace for "Plugins" metadata.
        public enum Plugins {
            /// Request type for "Plugins".
            public typealias Input = Containerd_Services_Introspection_V1_PluginsRequest
            /// Response type for "Plugins".
            public typealias Output = Containerd_Services_Introspection_V1_PluginsResponse
            /// Descriptor for "Plugins".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "containerd.services.introspection.v1.Introspection"),
                method: "Plugins"
            )
        }
        /// Namespace for "Server" metadata.
        public enum Server {
            /// Request type for "Server".
            public typealias Input = SwiftProtobuf.Google_Protobuf_Empty
            /// Response type for "Server".
            public typealias Output = Containerd_Services_Introspection_V1_ServerResponse
            /// Descriptor for "Server".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "containerd.services.introspection.v1.Introspection"),
                method: "Server"
            )
        }
        /// Namespace for "PluginInfo" metadata.
        public enum PluginInfo {
            /// Request type for "PluginInfo".
            public typealias Input = Containerd_Services_Introspection_V1_PluginInfoRequest
            /// Response type for "PluginInfo".
            public typealias Output = Containerd_Services_Introspection_V1_PluginInfoResponse
            /// Descriptor for "PluginInfo".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "containerd.services.introspection.v1.Introspection"),
                method: "PluginInfo"
            )
        }
        /// Descriptors for all methods in the "containerd.services.introspection.v1.Introspection" service.
        public static let descriptors: [GRPCCore.MethodDescriptor] = [
            Plugins.descriptor,
            Server.descriptor,
            PluginInfo.descriptor
        ]
    }
}

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension GRPCCore.ServiceDescriptor {
    /// Service descriptor for the "containerd.services.introspection.v1.Introspection" service.
    public static let containerd_services_introspection_v1_Introspection = GRPCCore.ServiceDescriptor(fullyQualifiedService: "containerd.services.introspection.v1.Introspection")
}

// MARK: containerd.services.introspection.v1.Introspection (client)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Containerd_Services_Introspection_V1_Introspection {
    /// Generated client protocol for the "containerd.services.introspection.v1.Introspection" service.
    ///
    /// You don't need to implement this protocol directly, use the generated
    /// implementation, ``Client``.
    public protocol ClientProtocol: Sendable {
        /// Call the "Plugins" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Plugins returns a list of plugins in containerd.
        /// > 
        /// > Clients can use this to detect features and capabilities when using
        /// > containerd.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Containerd_Services_Introspection_V1_PluginsRequest` message.
        ///   - serializer: A serializer for `Containerd_Services_Introspection_V1_PluginsRequest` messages.
        ///   - deserializer: A deserializer for `Containerd_Services_Introspection_V1_PluginsResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func plugins<Result>(
            request: GRPCCore.ClientRequest<Containerd_Services_Introspection_V1_PluginsRequest>,
            serializer: some GRPCCore.MessageSerializer<Containerd_Services_Introspection_V1_PluginsRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Containerd_Services_Introspection_V1_PluginsResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Containerd_Services_Introspection_V1_PluginsResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "Server" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Server returns information about the containerd server
        ///
        /// - Parameters:
        ///   - request: A request containing a single `SwiftProtobuf.Google_Protobuf_Empty` message.
        ///   - serializer: A serializer for `SwiftProtobuf.Google_Protobuf_Empty` messages.
        ///   - deserializer: A deserializer for `Containerd_Services_Introspection_V1_ServerResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func server<Result>(
            request: GRPCCore.ClientRequest<SwiftProtobuf.Google_Protobuf_Empty>,
            serializer: some GRPCCore.MessageSerializer<SwiftProtobuf.Google_Protobuf_Empty>,
            deserializer: some GRPCCore.MessageDeserializer<Containerd_Services_Introspection_V1_ServerResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Containerd_Services_Introspection_V1_ServerResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "PluginInfo" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > PluginInfo returns information directly from a plugin if the plugin supports it
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Containerd_Services_Introspection_V1_PluginInfoRequest` message.
        ///   - serializer: A serializer for `Containerd_Services_Introspection_V1_PluginInfoRequest` messages.
        ///   - deserializer: A deserializer for `Containerd_Services_Introspection_V1_PluginInfoResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func pluginInfo<Result>(
            request: GRPCCore.ClientRequest<Containerd_Services_Introspection_V1_PluginInfoRequest>,
            serializer: some GRPCCore.MessageSerializer<Containerd_Services_Introspection_V1_PluginInfoRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Containerd_Services_Introspection_V1_PluginInfoResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Containerd_Services_Introspection_V1_PluginInfoResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable
    }

    /// Generated client for the "containerd.services.introspection.v1.Introspection" service.
    ///
    /// The ``Client`` provides an implementation of ``ClientProtocol`` which wraps
    /// a `GRPCCore.GRPCCClient`. The underlying `GRPCClient` provides the long-lived
    /// means of communication with the remote peer.
    public struct Client<Transport>: ClientProtocol where Transport: GRPCCore.ClientTransport {
        private let client: GRPCCore.GRPCClient<Transport>

        /// Creates a new client wrapping the provided `GRPCCore.GRPCClient`.
        ///
        /// - Parameters:
        ///   - client: A `GRPCCore.GRPCClient` providing a communication channel to the service.
        public init(wrapping client: GRPCCore.GRPCClient<Transport>) {
            self.client = client
        }

        /// Call the "Plugins" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Plugins returns a list of plugins in containerd.
        /// > 
        /// > Clients can use this to detect features and capabilities when using
        /// > containerd.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Containerd_Services_Introspection_V1_PluginsRequest` message.
        ///   - serializer: A serializer for `Containerd_Services_Introspection_V1_PluginsRequest` messages.
        ///   - deserializer: A deserializer for `Containerd_Services_Introspection_V1_PluginsResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func plugins<Result>(
            request: GRPCCore.ClientRequest<Containerd_Services_Introspection_V1_PluginsRequest>,
            serializer: some GRPCCore.MessageSerializer<Containerd_Services_Introspection_V1_PluginsRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Containerd_Services_Introspection_V1_PluginsResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Containerd_Services_Introspection_V1_PluginsResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Containerd_Services_Introspection_V1_Introspection.Method.Plugins.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "Server" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Server returns information about the containerd server
        ///
        /// - Parameters:
        ///   - request: A request containing a single `SwiftProtobuf.Google_Protobuf_Empty` message.
        ///   - serializer: A serializer for `SwiftProtobuf.Google_Protobuf_Empty` messages.
        ///   - deserializer: A deserializer for `Containerd_Services_Introspection_V1_ServerResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func server<Result>(
            request: GRPCCore.ClientRequest<SwiftProtobuf.Google_Protobuf_Empty>,
            serializer: some GRPCCore.MessageSerializer<SwiftProtobuf.Google_Protobuf_Empty>,
            deserializer: some GRPCCore.MessageDeserializer<Containerd_Services_Introspection_V1_ServerResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Containerd_Services_Introspection_V1_ServerResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Containerd_Services_Introspection_V1_Introspection.Method.Server.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "PluginInfo" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > PluginInfo returns information directly from a plugin if the plugin supports it
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Containerd_Services_Introspection_V1_PluginInfoRequest` message.
        ///   - serializer: A serializer for `Containerd_Services_Introspection_V1_PluginInfoRequest` messages.
        ///   - deserializer: A deserializer for `Containerd_Services_Introspection_V1_PluginInfoResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func pluginInfo<Result>(
            request: GRPCCore.ClientRequest<Containerd_Services_Introspection_V1_PluginInfoRequest>,
            serializer: some GRPCCore.MessageSerializer<Containerd_Services_Introspection_V1_PluginInfoRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Containerd_Services_Introspection_V1_PluginInfoResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Containerd_Services_Introspection_V1_PluginInfoResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Containerd_Services_Introspection_V1_Introspection.Method.PluginInfo.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }
    }
}

// Helpers providing default arguments to 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Containerd_Services_Introspection_V1_Introspection.ClientProtocol {
    /// Call the "Plugins" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Plugins returns a list of plugins in containerd.
    /// > 
    /// > Clients can use this to detect features and capabilities when using
    /// > containerd.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Containerd_Services_Introspection_V1_PluginsRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func plugins<Result>(
        request: GRPCCore.ClientRequest<Containerd_Services_Introspection_V1_PluginsRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Containerd_Services_Introspection_V1_PluginsResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.plugins(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Containerd_Services_Introspection_V1_PluginsRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Containerd_Services_Introspection_V1_PluginsResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "Server" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Server returns information about the containerd server
    ///
    /// - Parameters:
    ///   - request: A request containing a single `SwiftProtobuf.Google_Protobuf_Empty` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func server<Result>(
        request: GRPCCore.ClientRequest<SwiftProtobuf.Google_Protobuf_Empty>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Containerd_Services_Introspection_V1_ServerResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.server(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<SwiftProtobuf.Google_Protobuf_Empty>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Containerd_Services_Introspection_V1_ServerResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "PluginInfo" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > PluginInfo returns information directly from a plugin if the plugin supports it
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Containerd_Services_Introspection_V1_PluginInfoRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func pluginInfo<Result>(
        request: GRPCCore.ClientRequest<Containerd_Services_Introspection_V1_PluginInfoRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Containerd_Services_Introspection_V1_PluginInfoResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.pluginInfo(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Containerd_Services_Introspection_V1_PluginInfoRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Containerd_Services_Introspection_V1_PluginInfoResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }
}

// Helpers providing sugared APIs for 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Containerd_Services_Introspection_V1_Introspection.ClientProtocol {
    /// Call the "Plugins" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Plugins returns a list of plugins in containerd.
    /// > 
    /// > Clients can use this to detect features and capabilities when using
    /// > containerd.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func plugins<Result>(
        _ message: Containerd_Services_Introspection_V1_PluginsRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Containerd_Services_Introspection_V1_PluginsResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Containerd_Services_Introspection_V1_PluginsRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.plugins(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "Server" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Server returns information about the containerd server
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func server<Result>(
        _ message: SwiftProtobuf.Google_Protobuf_Empty,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Containerd_Services_Introspection_V1_ServerResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<SwiftProtobuf.Google_Protobuf_Empty>(
            message: message,
            metadata: metadata
        )
        return try await self.server(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "PluginInfo" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > PluginInfo returns information directly from a plugin if the plugin supports it
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func pluginInfo<Result>(
        _ message: Containerd_Services_Introspection_V1_PluginInfoRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Containerd_Services_Introspection_V1_PluginInfoResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Containerd_Services_Introspection_V1_PluginInfoRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.pluginInfo(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }
}