//
//Copyright The containerd Authors.
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the gRPC Swift generator plugin for the protocol buffer compiler.
// Source: github.com/containerd/containerd/api/services/introspection/v1/introspection.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/grpc/grpc-swift

import GRPCCore
import GRPCProtobuf
import SwiftProtobuf

// MARK: - containerd.services.introspection.v1.Introspection

/// Namespace containing generated types for the "containerd.services.introspection.v1.Introspection" service.
public enum Containerd_Services_Introspection_V1_Introspection {
    /// Service descriptor for the "containerd.services.introspection.v1.Introspection" service.
    public static let descriptor = GRPCCore.ServiceDescriptor(fullyQualifiedService: "containerd.services.introspection.v1.Introspection")
    /// Namespace for method metadata.
    public enum Method {
        /// Namespace for "Plugins" metadata.
        public enum Plugins {
            /// Request type for "Plugins".
            public typealias Input = Containerd_Services_Introspection_V1_PluginsRequest
            /// Response type for "Plugins".
            public typealias Output = Containerd_Services_Introspection_V1_PluginsResponse
            /// Descriptor for "Plugins".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "containerd.services.introspection.v1.Introspection"),
                method: "Plugins"
            )
        }
        /// Namespace for "Server" metadata.
        public enum Server {
            /// Request type for "Server".
            public typealias Input = SwiftProtobuf.Google_Protobuf_Empty
            /// Response type for "Server".
            public typealias Output = Containerd_Services_Introspection_V1_ServerResponse
            /// Descriptor for "Server".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "containerd.services.introspection.v1.Introspection"),
                method: "Server"
            )
        }
        /// Namespace for "PluginInfo" metadata.
        public enum PluginInfo {
            /// Request type for "PluginInfo".
            public typealias Input = Containerd_Services_Introspection_V1_PluginInfoRequest
            /// Response type for "PluginInfo".
            public typealias Output = Containerd_Services_Introspection_V1_PluginInfoResponse
            /// Descriptor for "PluginInfo".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "containerd.services.introspection.v1.Introspection"),
                method: "PluginInfo"
            )
        }
        /// Descriptors for all methods in the "containerd.services.introspection.v1.Introspection" service.
        public static let descriptors: [GRPCCore.MethodDescriptor] = [
            Plugins.descriptor,
            Server.descriptor,
            PluginInfo.descriptor
        ]
    }
}

extension GRPCCore.ServiceDescriptor {
    /// Service descriptor for the "containerd.services.introspection.v1.Introspection" service.
    public static let containerd_services_introspection_v1_Introspection = GRPCCore.ServiceDescriptor(fullyQualifiedService: "containerd.services.introspection.v1.Introspection")
}

// MARK: containerd.services.introspection.v1.Introspection (server)

extension Containerd_Services_Introspection_V1_Introspection {
    /// Streaming variant of the service protocol for the "containerd.services.introspection.v1.Introspection" service.
    ///
    /// This protocol is the lowest-level of the service protocols generated for this service
    /// giving you the most flexibility over the implementation of your service. This comes at
    /// the cost of more verbose and less strict APIs. Each RPC requires you to implement it in
    /// terms of a request stream and response stream. Where only a single request or response
    /// message is expected, you are responsible for enforcing this invariant is maintained.
    ///
    /// Where possible, prefer using the stricter, less-verbose ``ServiceProtocol``
    /// or ``SimpleServiceProtocol`` instead.
    public protocol StreamingServiceProtocol: GRPCCore.RegistrableRPCService {
        /// Handle the "Plugins" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Plugins returns a list of plugins in containerd.
        /// > 
        /// > Clients can use this to detect features and capabilities when using
        /// > containerd.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Containerd_Services_Introspection_V1_PluginsRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Containerd_Services_Introspection_V1_PluginsResponse` messages.
        func plugins(
            request: GRPCCore.StreamingServerRequest<Containerd_Services_Introspection_V1_PluginsRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Containerd_Services_Introspection_V1_PluginsResponse>

        /// Handle the "Server" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Server returns information about the containerd server
        ///
        /// - Parameters:
        ///   - request: A streaming request of `SwiftProtobuf.Google_Protobuf_Empty` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Containerd_Services_Introspection_V1_ServerResponse` messages.
        func server(
            request: GRPCCore.StreamingServerRequest<SwiftProtobuf.Google_Protobuf_Empty>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Containerd_Services_Introspection_V1_ServerResponse>

        /// Handle the "PluginInfo" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > PluginInfo returns information directly from a plugin if the plugin supports it
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Containerd_Services_Introspection_V1_PluginInfoRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Containerd_Services_Introspection_V1_PluginInfoResponse` messages.
        func pluginInfo(
            request: GRPCCore.StreamingServerRequest<Containerd_Services_Introspection_V1_PluginInfoRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Containerd_Services_Introspection_V1_PluginInfoResponse>
    }

    /// Service protocol for the "containerd.services.introspection.v1.Introspection" service.
    ///
    /// This protocol is higher level than ``StreamingServiceProtocol`` but lower level than
    /// the ``SimpleServiceProtocol``, it provides access to request and response metadata and
    /// trailing response metadata. If you don't need these then consider using
    /// the ``SimpleServiceProtocol``. If you need fine grained control over your RPCs then
    /// use ``StreamingServiceProtocol``.
    public protocol ServiceProtocol: Containerd_Services_Introspection_V1_Introspection.StreamingServiceProtocol {
        /// Handle the "Plugins" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Plugins returns a list of plugins in containerd.
        /// > 
        /// > Clients can use this to detect features and capabilities when using
        /// > containerd.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Containerd_Services_Introspection_V1_PluginsRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `Containerd_Services_Introspection_V1_PluginsResponse` message.
        func plugins(
            request: GRPCCore.ServerRequest<Containerd_Services_Introspection_V1_PluginsRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<Containerd_Services_Introspection_V1_PluginsResponse>

        /// Handle the "Server" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Server returns information about the containerd server
        ///
        /// - Parameters:
        ///   - request: A request containing a single `SwiftProtobuf.Google_Protobuf_Empty` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `Containerd_Services_Introspection_V1_ServerResponse` message.
        func server(
            request: GRPCCore.ServerRequest<SwiftProtobuf.Google_Protobuf_Empty>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<Containerd_Services_Introspection_V1_ServerResponse>

        /// Handle the "PluginInfo" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > PluginInfo returns information directly from a plugin if the plugin supports it
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Containerd_Services_Introspection_V1_PluginInfoRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `Containerd_Services_Introspection_V1_PluginInfoResponse` message.
        func pluginInfo(
            request: GRPCCore.ServerRequest<Containerd_Services_Introspection_V1_PluginInfoRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<Containerd_Services_Introspection_V1_PluginInfoResponse>
    }

    /// Simple service protocol for the "containerd.services.introspection.v1.Introspection" service.
    ///
    /// This is the highest level protocol for the service. The API is the easiest to use but
    /// doesn't provide access to request or response metadata. If you need access to these
    /// then use ``ServiceProtocol`` instead.
    public protocol SimpleServiceProtocol: Containerd_Services_Introspection_V1_Introspection.ServiceProtocol {
        /// Handle the "Plugins" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Plugins returns a list of plugins in containerd.
        /// > 
        /// > Clients can use this to detect features and capabilities when using
        /// > containerd.
        ///
        /// - Parameters:
        ///   - request: A `Containerd_Services_Introspection_V1_PluginsRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `Containerd_Services_Introspection_V1_PluginsResponse` to respond with.
        func plugins(
            request: Containerd_Services_Introspection_V1_PluginsRequest,
            context: GRPCCore.ServerContext
        ) async throws -> Containerd_Services_Introspection_V1_PluginsResponse

        /// Handle the "Server" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Server returns information about the containerd server
        ///
        /// - Parameters:
        ///   - request: A `SwiftProtobuf.Google_Protobuf_Empty` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `Containerd_Services_Introspection_V1_ServerResponse` to respond with.
        func server(
            request: SwiftProtobuf.Google_Protobuf_Empty,
            context: GRPCCore.ServerContext
        ) async throws -> Containerd_Services_Introspection_V1_ServerResponse

        /// Handle the "PluginInfo" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > PluginInfo returns information directly from a plugin if the plugin supports it
        ///
        /// - Parameters:
        ///   - request: A `Containerd_Services_Introspection_V1_PluginInfoRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `Containerd_Services_Introspection_V1_PluginInfoResponse` to respond with.
        func pluginInfo(
            request: Containerd_Services_Introspection_V1_PluginInfoRequest,
            context: GRPCCore.ServerContext
        ) async throws -> Containerd_Services_Introspection_V1_PluginInfoResponse
    }
}

// Default implementation of 'registerMethods(with:)'.
extension Containerd_Services_Introspection_V1_Introspection.StreamingServiceProtocol {
    public func registerMethods<Transport>(with router: inout GRPCCore.RPCRouter<Transport>) where Transport: GRPCCore.ServerTransport {
        router.registerHandler(
            forMethod: Containerd_Services_Introspection_V1_Introspection.Method.Plugins.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Containerd_Services_Introspection_V1_PluginsRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Containerd_Services_Introspection_V1_PluginsResponse>(),
            handler: { request, context in
                try await self.plugins(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: Containerd_Services_Introspection_V1_Introspection.Method.Server.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<SwiftProtobuf.Google_Protobuf_Empty>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Containerd_Services_Introspection_V1_ServerResponse>(),
            handler: { request, context in
                try await self.server(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: Containerd_Services_Introspection_V1_Introspection.Method.PluginInfo.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Containerd_Services_Introspection_V1_PluginInfoRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Containerd_Services_Introspection_V1_PluginInfoResponse>(),
            handler: { request, context in
                try await self.pluginInfo(
                    request: request,
                    context: context
                )
            }
        )
    }
}

// Default implementation of streaming methods from 'StreamingServiceProtocol'.
extension Containerd_Services_Introspection_V1_Introspection.ServiceProtocol {
    public func plugins(
        request: GRPCCore.StreamingServerRequest<Containerd_Services_Introspection_V1_PluginsRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Containerd_Services_Introspection_V1_PluginsResponse> {
        let response = try await self.plugins(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }

    public func server(
        request: GRPCCore.StreamingServerRequest<SwiftProtobuf.Google_Protobuf_Empty>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Containerd_Services_Introspection_V1_ServerResponse> {
        let response = try await self.server(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }

    public func pluginInfo(
        request: GRPCCore.StreamingServerRequest<Containerd_Services_Introspection_V1_PluginInfoRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Containerd_Services_Introspection_V1_PluginInfoResponse> {
        let response = try await self.pluginInfo(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }
}

// Default implementation of methods from 'ServiceProtocol'.
extension Containerd_Services_Introspection_V1_Introspection.SimpleServiceProtocol {
    public func plugins(
        request: GRPCCore.ServerRequest<Containerd_Services_Introspection_V1_PluginsRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<Containerd_Services_Introspection_V1_PluginsResponse> {
        return GRPCCore.ServerResponse<Containerd_Services_Introspection_V1_PluginsResponse>(
            message: try await self.plugins(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }

    public func server(
        request: GRPCCore.ServerRequest<SwiftProtobuf.Google_Protobuf_Empty>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<Containerd_Services_Introspection_V1_ServerResponse> {
        return GRPCCore.ServerResponse<Containerd_Services_Introspection_V1_ServerResponse>(
            message: try await self.server(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }

    public func pluginInfo(
        request: GRPCCore.ServerRequest<Containerd_Services_Introspection_V1_PluginInfoRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<Containerd_Services_Introspection_V1_PluginInfoResponse> {
        return GRPCCore.ServerResponse<Containerd_Services_Introspection_V1_PluginInfoResponse>(
            message: try await self.pluginInfo(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }
}

// MARK: containerd.services.introspection.v1.Introspection (client)

extension Containerd_Services_Introspection_V1_Introspection {
    /// Generated client protocol for the "containerd.services.introspection.v1.Introspection" service.
    ///
    /// You don't need to implement this protocol directly, use the generated
    /// implementation, ``Client``.
    public protocol ClientProtocol: Sendable {
        /// Call the "Plugins" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Plugins returns a list of plugins in containerd.
        /// > 
        /// > Clients can use this to detect features and capabilities when using
        /// > containerd.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Containerd_Services_Introspection_V1_PluginsRequest` message.
        ///   - serializer: A serializer for `Containerd_Services_Introspection_V1_PluginsRequest` messages.
        ///   - deserializer: A deserializer for `Containerd_Services_Introspection_V1_PluginsResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func plugins<Result>(
            request: GRPCCore.ClientRequest<Containerd_Services_Introspection_V1_PluginsRequest>,
            serializer: some GRPCCore.MessageSerializer<Containerd_Services_Introspection_V1_PluginsRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Containerd_Services_Introspection_V1_PluginsResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Containerd_Services_Introspection_V1_PluginsResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "Server" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Server returns information about the containerd server
        ///
        /// - Parameters:
        ///   - request: A request containing a single `SwiftProtobuf.Google_Protobuf_Empty` message.
        ///   - serializer: A serializer for `SwiftProtobuf.Google_Protobuf_Empty` messages.
        ///   - deserializer: A deserializer for `Containerd_Services_Introspection_V1_ServerResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func server<Result>(
            request: GRPCCore.ClientRequest<SwiftProtobuf.Google_Protobuf_Empty>,
            serializer: some GRPCCore.MessageSerializer<SwiftProtobuf.Google_Protobuf_Empty>,
            deserializer: some GRPCCore.MessageDeserializer<Containerd_Services_Introspection_V1_ServerResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Containerd_Services_Introspection_V1_ServerResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "PluginInfo" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > PluginInfo returns information directly from a plugin if the plugin supports it
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Containerd_Services_Introspection_V1_PluginInfoRequest` message.
        ///   - serializer: A serializer for `Containerd_Services_Introspection_V1_PluginInfoRequest` messages.
        ///   - deserializer: A deserializer for `Containerd_Services_Introspection_V1_PluginInfoResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func pluginInfo<Result>(
            request: GRPCCore.ClientRequest<Containerd_Services_Introspection_V1_PluginInfoRequest>,
            serializer: some GRPCCore.MessageSerializer<Containerd_Services_Introspection_V1_PluginInfoRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Containerd_Services_Introspection_V1_PluginInfoResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Containerd_Services_Introspection_V1_PluginInfoResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable
    }

    /// Generated client for the "containerd.services.introspection.v1.Introspection" service.
    ///
    /// The ``Client`` provides an implementation of ``ClientProtocol`` which wraps
    /// a `GRPCCore.GRPCCClient`. The underlying `GRPCClient` provides the long-lived
    /// means of communication with the remote peer.
    public struct Client<Transport>: ClientProtocol where Transport: GRPCCore.ClientTransport {
        private let client: GRPCCore.GRPCClient<Transport>

        /// Creates a new client wrapping the provided `GRPCCore.GRPCClient`.
        ///
        /// - Parameters:
        ///   - client: A `GRPCCore.GRPCClient` providing a communication channel to the service.
        public init(wrapping client: GRPCCore.GRPCClient<Transport>) {
            self.client = client
        }

        /// Call the "Plugins" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Plugins returns a list of plugins in containerd.
        /// > 
        /// > Clients can use this to detect features and capabilities when using
        /// > containerd.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Containerd_Services_Introspection_V1_PluginsRequest` message.
        ///   - serializer: A serializer for `Containerd_Services_Introspection_V1_PluginsRequest` messages.
        ///   - deserializer: A deserializer for `Containerd_Services_Introspection_V1_PluginsResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func plugins<Result>(
            request: GRPCCore.ClientRequest<Containerd_Services_Introspection_V1_PluginsRequest>,
            serializer: some GRPCCore.MessageSerializer<Containerd_Services_Introspection_V1_PluginsRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Containerd_Services_Introspection_V1_PluginsResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Containerd_Services_Introspection_V1_PluginsResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Containerd_Services_Introspection_V1_Introspection.Method.Plugins.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "Server" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Server returns information about the containerd server
        ///
        /// - Parameters:
        ///   - request: A request containing a single `SwiftProtobuf.Google_Protobuf_Empty` message.
        ///   - serializer: A serializer for `SwiftProtobuf.Google_Protobuf_Empty` messages.
        ///   - deserializer: A deserializer for `Containerd_Services_Introspection_V1_ServerResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func server<Result>(
            request: GRPCCore.ClientRequest<SwiftProtobuf.Google_Protobuf_Empty>,
            serializer: some GRPCCore.MessageSerializer<SwiftProtobuf.Google_Protobuf_Empty>,
            deserializer: some GRPCCore.MessageDeserializer<Containerd_Services_Introspection_V1_ServerResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Containerd_Services_Introspection_V1_ServerResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Containerd_Services_Introspection_V1_Introspection.Method.Server.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "PluginInfo" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > PluginInfo returns information directly from a plugin if the plugin supports it
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Containerd_Services_Introspection_V1_PluginInfoRequest` message.
        ///   - serializer: A serializer for `Containerd_Services_Introspection_V1_PluginInfoRequest` messages.
        ///   - deserializer: A deserializer for `Containerd_Services_Introspection_V1_PluginInfoResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func pluginInfo<Result>(
            request: GRPCCore.ClientRequest<Containerd_Services_Introspection_V1_PluginInfoRequest>,
            serializer: some GRPCCore.MessageSerializer<Containerd_Services_Introspection_V1_PluginInfoRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Containerd_Services_Introspection_V1_PluginInfoResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Containerd_Services_Introspection_V1_PluginInfoResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Containerd_Services_Introspection_V1_Introspection.Method.PluginInfo.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }
    }
}

// Helpers providing default arguments to 'ClientProtocol' methods.
extension Containerd_Services_Introspection_V1_Introspection.ClientProtocol {
    /// Call the "Plugins" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Plugins returns a list of plugins in containerd.
    /// > 
    /// > Clients can use this to detect features and capabilities when using
    /// > containerd.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Containerd_Services_Introspection_V1_PluginsRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func plugins<Result>(
        request: GRPCCore.ClientRequest<Containerd_Services_Introspection_V1_PluginsRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Containerd_Services_Introspection_V1_PluginsResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.plugins(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Containerd_Services_Introspection_V1_PluginsRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Containerd_Services_Introspection_V1_PluginsResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "Server" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Server returns information about the containerd server
    ///
    /// - Parameters:
    ///   - request: A request containing a single `SwiftProtobuf.Google_Protobuf_Empty` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func server<Result>(
        request: GRPCCore.ClientRequest<SwiftProtobuf.Google_Protobuf_Empty>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Containerd_Services_Introspection_V1_ServerResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.server(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<SwiftProtobuf.Google_Protobuf_Empty>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Containerd_Services_Introspection_V1_ServerResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "PluginInfo" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > PluginInfo returns information directly from a plugin if the plugin supports it
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Containerd_Services_Introspection_V1_PluginInfoRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func pluginInfo<Result>(
        request: GRPCCore.ClientRequest<Containerd_Services_Introspection_V1_PluginInfoRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Containerd_Services_Introspection_V1_PluginInfoResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.pluginInfo(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Containerd_Services_Introspection_V1_PluginInfoRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Containerd_Services_Introspection_V1_PluginInfoResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }
}

// Helpers providing sugared APIs for 'ClientProtocol' methods.
extension Containerd_Services_Introspection_V1_Introspection.ClientProtocol {
    /// Call the "Plugins" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Plugins returns a list of plugins in containerd.
    /// > 
    /// > Clients can use this to detect features and capabilities when using
    /// > containerd.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func plugins<Result>(
        _ message: Containerd_Services_Introspection_V1_PluginsRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Containerd_Services_Introspection_V1_PluginsResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Containerd_Services_Introspection_V1_PluginsRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.plugins(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "Server" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Server returns information about the containerd server
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func server<Result>(
        _ message: SwiftProtobuf.Google_Protobuf_Empty,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Containerd_Services_Introspection_V1_ServerResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<SwiftProtobuf.Google_Protobuf_Empty>(
            message: message,
            metadata: metadata
        )
        return try await self.server(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "PluginInfo" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > PluginInfo returns information directly from a plugin if the plugin supports it
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func pluginInfo<Result>(
        _ message: Containerd_Services_Introspection_V1_PluginInfoRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Containerd_Services_Introspection_V1_PluginInfoResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Containerd_Services_Introspection_V1_PluginInfoRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.pluginInfo(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }
}