---
all:
  children:
    ci:
      hosts:
        kb-ubuntu-24.local:
          ansible_user: konstantinbe
          ansible_connection: ssh
        kb-windows-11.local:
          ansible_user: konstantinbe
          ansible_connection: ssh
          ansible_shell_type: powershell
        kb-macos-26.local:
          ansible_user: konstantinbe
          ansible_connection: ssh
