---
all:
  children:
    ci:
      hosts:
        kb-cli-ubuntu-24-01:
          ansible_host: kb-ubuntu-24.local
        kb-cli-windows-11-01:
          ansible_host: kb-windows-11.local
          ansible_shell_type: powershell
        kb-cli-macos-26-01:
          ansible_host: kb-macos-26.local
        kb-agent-macos-26-01:
          ansible_host: mac-mini.local
    kb:
      hosts:
        kb-cli-ubuntu-24-01:
        kb-cli-windows-11-01:
        kb-cli-macos-26-01:
        kb-agent-macos-26-01:
    wendy_cli:
      hosts:
        kb-cli-ubuntu-24-01:
        kb-cli-windows-11-01:
        kb-cli-macos-26-01:
    wendy_agent:
      hosts:
        kb-agent-macos-26-01:
