---
# Copy to local.yml and keep local.yml out of git.
all:
  children:
    ci:
      hosts:
        macos-runner.local:
          ansible_user: your-user
          ansible_connection: ssh
        ubuntu-runner.local:
          ansible_user: your-user
          ansible_connection: ssh
        windows-runner.local:
          ansible_user: your-user
          ansible_connection: ssh
          ansible_shell_type: powershell
