---
all:
  children:
    ci:
      hosts:
        wendy-developer-ubuntu-24-01:
          ansible_host: wendy-developer-ubuntu
        wendy-developer-windows-11-01:
          ansible_host: wendy-windows
          ansible_shell_type: powershell
        wendy-developer-macos-26-01:
          ansible_host: wendys-mac-mini
        wendy-daemon-macos-26-01:
          ansible_host: wendys-mac-mini-2
    pending:
      hosts:
        wendy-daemon-ubuntu-01: {}
    wendy:
      hosts:
        wendy-developer-ubuntu-24-01:
        wendy-developer-windows-11-01:
        wendy-developer-macos-26-01:
        wendy-daemon-macos-26-01:
        wendy-daemon-ubuntu-01:
    wendy_developer:
      hosts:
        wendy-developer-ubuntu-24-01:
        wendy-developer-windows-11-01:
        wendy-developer-macos-26-01:
    wendy_daemon:
      hosts:
        wendy-daemon-macos-26-01:
        wendy-daemon-ubuntu-01:
