---
- name: Run Pi coding agent info
  ansible.builtin.include_tasks:
    file: info.yml
    apply:
      tags: info
  tags: [info]

- name: Include macOS Pi coding agent tasks
  ansible.builtin.include_tasks:
    file: macos.yml
    apply:
      tags: [pi, pi_coding_agent]
  when: ansible_facts.system == 'Darwin'
  tags: [pi, pi_coding_agent]

- name: Include Ubuntu Pi coding agent tasks
  ansible.builtin.include_tasks:
    file: ubuntu.yml
    apply:
      tags: [pi, pi_coding_agent]
  when: ansible_facts.distribution == 'Ubuntu'
  tags: [pi, pi_coding_agent]

- name: Include Windows Pi coding agent tasks
  ansible.builtin.include_tasks:
    file: windows.yml
    apply:
      tags: [pi, pi_coding_agent]
  when: ansible_facts.os_family == 'Windows'
  tags: [pi, pi_coding_agent]
