//
//Copyright The containerd Authors.
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the gRPC Swift generator plugin for the protocol buffer compiler.
// Source: github.com/containerd/containerd/api/services/events/v1/events.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/grpc/grpc-swift

import GRPCCore
import GRPCProtobuf
import SwiftProtobuf

// MARK: - containerd.services.events.v1.Events

/// Namespace containing generated types for the "containerd.services.events.v1.Events" service.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
public enum Containerd_Services_Events_V1_Events {
    /// Service descriptor for the "containerd.services.events.v1.Events" service.
    public static let descriptor = GRPCCore.ServiceDescriptor(fullyQualifiedService: "containerd.services.events.v1.Events")
    /// Namespace for method metadata.
    public enum Method {
        /// Namespace for "Publish" metadata.
        public enum Publish {
            /// Request type for "Publish".
            public typealias Input = Containerd_Services_Events_V1_PublishRequest
            /// Response type for "Publish".
            public typealias Output = SwiftProtobuf.Google_Protobuf_Empty
            /// Descriptor for "Publish".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "containerd.services.events.v1.Events"),
                method: "Publish"
            )
        }
        /// Namespace for "Forward" metadata.
        public enum Forward {
            /// Request type for "Forward".
            public typealias Input = Containerd_Services_Events_V1_ForwardRequest
            /// Response type for "Forward".
            public typealias Output = SwiftProtobuf.Google_Protobuf_Empty
            /// Descriptor for "Forward".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "containerd.services.events.v1.Events"),
                method: "Forward"
            )
        }
        /// Namespace for "Subscribe" metadata.
        public enum Subscribe {
            /// Request type for "Subscribe".
            public typealias Input = Containerd_Services_Events_V1_SubscribeRequest
            /// Response type for "Subscribe".
            public typealias Output = Containerd_Types_Envelope
            /// Descriptor for "Subscribe".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "containerd.services.events.v1.Events"),
                method: "Subscribe"
            )
        }
        /// Descriptors for all methods in the "containerd.services.events.v1.Events" service.
        public static let descriptors: [GRPCCore.MethodDescriptor] = [
            Publish.descriptor,
            Forward.descriptor,
            Subscribe.descriptor
        ]
    }
}

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension GRPCCore.ServiceDescriptor {
    /// Service descriptor for the "containerd.services.events.v1.Events" service.
    public static let containerd_services_events_v1_Events = GRPCCore.ServiceDescriptor(fullyQualifiedService: "containerd.services.events.v1.Events")
}

// MARK: containerd.services.events.v1.Events (client)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Containerd_Services_Events_V1_Events {
    /// Generated client protocol for the "containerd.services.events.v1.Events" service.
    ///
    /// You don't need to implement this protocol directly, use the generated
    /// implementation, ``Client``.
    public protocol ClientProtocol: Sendable {
        /// Call the "Publish" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Publish an event to a topic.
        /// > 
        /// > The event will be packed into a timestamp envelope with the namespace
        /// > introspected from the context. The envelope will then be dispatched.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Containerd_Services_Events_V1_PublishRequest` message.
        ///   - serializer: A serializer for `Containerd_Services_Events_V1_PublishRequest` messages.
        ///   - deserializer: A deserializer for `SwiftProtobuf.Google_Protobuf_Empty` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func publish<Result>(
            request: GRPCCore.ClientRequest<Containerd_Services_Events_V1_PublishRequest>,
            serializer: some GRPCCore.MessageSerializer<Containerd_Services_Events_V1_PublishRequest>,
            deserializer: some GRPCCore.MessageDeserializer<SwiftProtobuf.Google_Protobuf_Empty>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<SwiftProtobuf.Google_Protobuf_Empty>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "Forward" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Forward sends an event that has already been packaged into an envelope
        /// > with a timestamp and namespace.
        /// > 
        /// > This is useful if earlier timestamping is required or when forwarding on
        /// > behalf of another component, namespace or publisher.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Containerd_Services_Events_V1_ForwardRequest` message.
        ///   - serializer: A serializer for `Containerd_Services_Events_V1_ForwardRequest` messages.
        ///   - deserializer: A deserializer for `SwiftProtobuf.Google_Protobuf_Empty` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func forward<Result>(
            request: GRPCCore.ClientRequest<Containerd_Services_Events_V1_ForwardRequest>,
            serializer: some GRPCCore.MessageSerializer<Containerd_Services_Events_V1_ForwardRequest>,
            deserializer: some GRPCCore.MessageDeserializer<SwiftProtobuf.Google_Protobuf_Empty>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<SwiftProtobuf.Google_Protobuf_Empty>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "Subscribe" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Subscribe to a stream of events, possibly returning only that match any
        /// > of the provided filters.
        /// > 
        /// > Unlike many other methods in containerd, subscribers will get messages
        /// > from all namespaces unless otherwise specified. If this is not desired,
        /// > a filter can be provided in the format 'namespace==<namespace>' to
        /// > restrict the received events.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Containerd_Services_Events_V1_SubscribeRequest` message.
        ///   - serializer: A serializer for `Containerd_Services_Events_V1_SubscribeRequest` messages.
        ///   - deserializer: A deserializer for `Containerd_Types_Envelope` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func subscribe<Result>(
            request: GRPCCore.ClientRequest<Containerd_Services_Events_V1_SubscribeRequest>,
            serializer: some GRPCCore.MessageSerializer<Containerd_Services_Events_V1_SubscribeRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Containerd_Types_Envelope>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<Containerd_Types_Envelope>) async throws -> Result
        ) async throws -> Result where Result: Sendable
    }

    /// Generated client for the "containerd.services.events.v1.Events" service.
    ///
    /// The ``Client`` provides an implementation of ``ClientProtocol`` which wraps
    /// a `GRPCCore.GRPCCClient`. The underlying `GRPCClient` provides the long-lived
    /// means of communication with the remote peer.
    public struct Client<Transport>: ClientProtocol where Transport: GRPCCore.ClientTransport {
        private let client: GRPCCore.GRPCClient<Transport>

        /// Creates a new client wrapping the provided `GRPCCore.GRPCClient`.
        ///
        /// - Parameters:
        ///   - client: A `GRPCCore.GRPCClient` providing a communication channel to the service.
        public init(wrapping client: GRPCCore.GRPCClient<Transport>) {
            self.client = client
        }

        /// Call the "Publish" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Publish an event to a topic.
        /// > 
        /// > The event will be packed into a timestamp envelope with the namespace
        /// > introspected from the context. The envelope will then be dispatched.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Containerd_Services_Events_V1_PublishRequest` message.
        ///   - serializer: A serializer for `Containerd_Services_Events_V1_PublishRequest` messages.
        ///   - deserializer: A deserializer for `SwiftProtobuf.Google_Protobuf_Empty` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func publish<Result>(
            request: GRPCCore.ClientRequest<Containerd_Services_Events_V1_PublishRequest>,
            serializer: some GRPCCore.MessageSerializer<Containerd_Services_Events_V1_PublishRequest>,
            deserializer: some GRPCCore.MessageDeserializer<SwiftProtobuf.Google_Protobuf_Empty>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<SwiftProtobuf.Google_Protobuf_Empty>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Containerd_Services_Events_V1_Events.Method.Publish.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "Forward" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Forward sends an event that has already been packaged into an envelope
        /// > with a timestamp and namespace.
        /// > 
        /// > This is useful if earlier timestamping is required or when forwarding on
        /// > behalf of another component, namespace or publisher.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Containerd_Services_Events_V1_ForwardRequest` message.
        ///   - serializer: A serializer for `Containerd_Services_Events_V1_ForwardRequest` messages.
        ///   - deserializer: A deserializer for `SwiftProtobuf.Google_Protobuf_Empty` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func forward<Result>(
            request: GRPCCore.ClientRequest<Containerd_Services_Events_V1_ForwardRequest>,
            serializer: some GRPCCore.MessageSerializer<Containerd_Services_Events_V1_ForwardRequest>,
            deserializer: some GRPCCore.MessageDeserializer<SwiftProtobuf.Google_Protobuf_Empty>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<SwiftProtobuf.Google_Protobuf_Empty>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Containerd_Services_Events_V1_Events.Method.Forward.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "Subscribe" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Subscribe to a stream of events, possibly returning only that match any
        /// > of the provided filters.
        /// > 
        /// > Unlike many other methods in containerd, subscribers will get messages
        /// > from all namespaces unless otherwise specified. If this is not desired,
        /// > a filter can be provided in the format 'namespace==<namespace>' to
        /// > restrict the received events.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Containerd_Services_Events_V1_SubscribeRequest` message.
        ///   - serializer: A serializer for `Containerd_Services_Events_V1_SubscribeRequest` messages.
        ///   - deserializer: A deserializer for `Containerd_Types_Envelope` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func subscribe<Result>(
            request: GRPCCore.ClientRequest<Containerd_Services_Events_V1_SubscribeRequest>,
            serializer: some GRPCCore.MessageSerializer<Containerd_Services_Events_V1_SubscribeRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Containerd_Types_Envelope>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<Containerd_Types_Envelope>) async throws -> Result
        ) async throws -> Result where Result: Sendable {
            try await self.client.serverStreaming(
                request: request,
                descriptor: Containerd_Services_Events_V1_Events.Method.Subscribe.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }
    }
}

// Helpers providing default arguments to 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Containerd_Services_Events_V1_Events.ClientProtocol {
    /// Call the "Publish" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Publish an event to a topic.
    /// > 
    /// > The event will be packed into a timestamp envelope with the namespace
    /// > introspected from the context. The envelope will then be dispatched.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Containerd_Services_Events_V1_PublishRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func publish<Result>(
        request: GRPCCore.ClientRequest<Containerd_Services_Events_V1_PublishRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<SwiftProtobuf.Google_Protobuf_Empty>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.publish(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Containerd_Services_Events_V1_PublishRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<SwiftProtobuf.Google_Protobuf_Empty>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "Forward" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Forward sends an event that has already been packaged into an envelope
    /// > with a timestamp and namespace.
    /// > 
    /// > This is useful if earlier timestamping is required or when forwarding on
    /// > behalf of another component, namespace or publisher.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Containerd_Services_Events_V1_ForwardRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func forward<Result>(
        request: GRPCCore.ClientRequest<Containerd_Services_Events_V1_ForwardRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<SwiftProtobuf.Google_Protobuf_Empty>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.forward(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Containerd_Services_Events_V1_ForwardRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<SwiftProtobuf.Google_Protobuf_Empty>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "Subscribe" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Subscribe to a stream of events, possibly returning only that match any
    /// > of the provided filters.
    /// > 
    /// > Unlike many other methods in containerd, subscribers will get messages
    /// > from all namespaces unless otherwise specified. If this is not desired,
    /// > a filter can be provided in the format 'namespace==<namespace>' to
    /// > restrict the received events.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Containerd_Services_Events_V1_SubscribeRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func subscribe<Result>(
        request: GRPCCore.ClientRequest<Containerd_Services_Events_V1_SubscribeRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<Containerd_Types_Envelope>) async throws -> Result
    ) async throws -> Result where Result: Sendable {
        try await self.subscribe(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Containerd_Services_Events_V1_SubscribeRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Containerd_Types_Envelope>(),
            options: options,
            onResponse: handleResponse
        )
    }
}

// Helpers providing sugared APIs for 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Containerd_Services_Events_V1_Events.ClientProtocol {
    /// Call the "Publish" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Publish an event to a topic.
    /// > 
    /// > The event will be packed into a timestamp envelope with the namespace
    /// > introspected from the context. The envelope will then be dispatched.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func publish<Result>(
        _ message: Containerd_Services_Events_V1_PublishRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<SwiftProtobuf.Google_Protobuf_Empty>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Containerd_Services_Events_V1_PublishRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.publish(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "Forward" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Forward sends an event that has already been packaged into an envelope
    /// > with a timestamp and namespace.
    /// > 
    /// > This is useful if earlier timestamping is required or when forwarding on
    /// > behalf of another component, namespace or publisher.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func forward<Result>(
        _ message: Containerd_Services_Events_V1_ForwardRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<SwiftProtobuf.Google_Protobuf_Empty>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Containerd_Services_Events_V1_ForwardRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.forward(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "Subscribe" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Subscribe to a stream of events, possibly returning only that match any
    /// > of the provided filters.
    /// > 
    /// > Unlike many other methods in containerd, subscribers will get messages
    /// > from all namespaces unless otherwise specified. If this is not desired,
    /// > a filter can be provided in the format 'namespace==<namespace>' to
    /// > restrict the received events.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func subscribe<Result>(
        _ message: Containerd_Services_Events_V1_SubscribeRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<Containerd_Types_Envelope>) async throws -> Result
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Containerd_Services_Events_V1_SubscribeRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.subscribe(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }
}