---
- name: Run GitHub runner info
  ansible.builtin.include_tasks:
    file: info.yml
    apply:
      tags: info
  tags: [info]

- name: Compose GitHub runner labels
  ansible.builtin.set_fact:
    github_runner_effective_labels: "{{ (github_runner_labels | default([])) + (github_runner_site_labels | default([])) + (github_runner_machine_labels | default([])) + (github_runner_platform_labels | default([])) }}"
  changed_when: false
  tags: [info, runner, github_runner]

- name: Include macOS GitHub runner tasks
  ansible.builtin.include_tasks:
    file: macos.yml
    apply:
      tags: [runner, github_runner]
  when: ansible_facts.system == 'Darwin'
  tags: [runner, github_runner]

- name: Include Ubuntu GitHub runner tasks
  ansible.builtin.include_tasks:
    file: ubuntu.yml
    apply:
      tags: [runner, github_runner]
  when: ansible_facts.distribution == 'Ubuntu'
  tags: [runner, github_runner]

- name: Include Windows GitHub runner tasks
  ansible.builtin.include_tasks:
    file: windows.yml
    apply:
      tags: [runner, github_runner]
  when: ansible_facts.os_family == 'Windows'
  tags: [runner, github_runner]
