name: Build products and release

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

# Add permissions needed for creating releases
permissions:
  contents: write

jobs:
  determine-version:
    name: Determine Version
    runs-on: [self-hosted, Linux, X64]
    outputs:
      version: ${{ steps.set-version.outputs.version }}
    steps:
      - name: Set version
        id: set-version
        run: |
          TIMESTAMP=$(date +'%Y.%m.%d-%H%M%S')

          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            VERSION="${TIMESTAMP}"
          else
            VERSION="${TIMESTAMP}-dev"
          fi

          echo "Setting version to $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

  build:
    needs: determine-version
    strategy:
      matrix:
        include:
          - platform: linux-static-musl-aarch64
            os: [self-hosted, Linux, X64]
            container: swift:6.2.0
            swift-sdk: aarch64-swift-linux-musl
            swift-sdk-url: https://download.swift.org/swift-6.2-release/static-sdk/swift-6.2-RELEASE/swift-6.2-RELEASE_static-linux-0.0.1.artifactbundle.tar.gz
            swift-sdk-checksum: d2225840e592389ca517bbf71652f7003dbf45ac35d1e57d98b9250368769378
          - platform: linux-static-musl-x86_64
            os: [self-hosted, Linux, X64]
            container: swift:6.2.0
            swift-sdk: x86_64-swift-linux-musl
            swift-sdk-url: https://download.swift.org/swift-6.2-release/static-sdk/swift-6.2-RELEASE/swift-6.2-RELEASE_static-linux-0.0.1.artifactbundle.tar.gz
            swift-sdk-checksum: d2225840e592389ca517bbf71652f7003dbf45ac35d1e57d98b9250368769378
          - platform: macos-arm64
            os: macos-15
            xcode-select: /Applications/Xcode_26.0.app

    name: ${{ matrix.platform }}
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}

    steps:
      - uses: actions/checkout@v4
      - name: Install Static Linux SDK
        if: ${{ matrix.swift-sdk-url != '' }}
        run: |
          swift sdk install ${{ matrix.swift-sdk-url }} --checksum ${{ matrix.swift-sdk-checksum }}
      - name: xcode-select
        if: ${{ matrix.xcode-select != '' }}
        run: |
          sudo xcode-select --switch ${{ matrix.xcode-select }}
      - name: Inject Version
        run: |
          # Use the version from the needs context
          echo "Using version: ${{ needs.determine-version.outputs.version }}"
          ./Scripts/inject-version.sh "${{ needs.determine-version.outputs.version }}"
      - name: Build
        shell: bash
        run: |
          args=(
            --configuration release
          )

          if [ -n "${{ matrix.swift-sdk }}" ]; then
            args+=(--swift-sdk "${{ matrix.swift-sdk }}")
          fi

          # Add optimization flags for wendy-agent builds
          if [ "${{ matrix.product }}" == "wendy-agent" ]; then
            args+=(-Xswiftc -whole-module-optimization)
            args+=(-Xlinker --gc-sections)
            args+=(-Xlinker --strip-all)
          fi

          swift build "${args[@]}"

          # Copy built binary to the output directory
          AGENT_OUTPUT_DIR=wendy-agent-${{ matrix.platform }}
          CLI_OUTPUT_DIR=wendy-cli-${{ matrix.platform }}
          BIN_PATH=$(swift build --show-bin-path "${args[@]}")
          mkdir $AGENT_OUTPUT_DIR
          mkdir $CLI_OUTPUT_DIR
          cp $BIN_PATH/wendy-agent $AGENT_OUTPUT_DIR/
          cp $BIN_PATH/wendy $CLI_OUTPUT_DIR/
          cp $BIN_PATH/wendy-helper $CLI_OUTPUT_DIR/
          cp $BIN_PATH/wendy-network-daemon $CLI_OUTPUT_DIR/

          # If a folder exists at $BIN_PATH/wendy-agent_wendy.bundle, copy it to output/
          if [ -d "$BIN_PATH/wendy-agent_wendy.bundle" ]; then
            cp -r $BIN_PATH/wendy-agent_wendy.bundle $CLI_OUTPUT_DIR/
          fi
      - name: Import P12 Certificate
        if: ${{ matrix.platform == 'macos-arm64' }}
        uses: apple-actions/import-codesign-certs@v3
        with: 
          p12-file-base64: ${{ secrets.APPSTORE_CERTIFICATES_FILE_BASE64 }}
          p12-password: ${{ secrets.APPSTORE_CERTIFICATES_PASSWORD }}
          keychain: notary-keychain
      - name: Setup Notary Profile
        if: ${{ matrix.platform == 'macos-arm64' }}
        run: |
          xcrun notarytool store-credentials "notary-profile" \
            --apple-id "${{ secrets.NOTARY_APPLE_ID }}" \
            --team-id "${{ secrets.NOTARY_TEAM_ID }}" \
            --password "${{ secrets.NOTARY_PASSWORD }}"
      - name: Codesign
        if: ${{ matrix.platform == 'macos-arm64' }}
        timeout-minutes: 10
        run: |
          ./Scripts/codesign.sh "wendy-cli-${{ matrix.platform }}/wendy"
      - name: Create tarball
        run: |
          TARBALL_NAME="wendy-cli-${{ matrix.platform }}-${{ needs.determine-version.outputs.version }}.tar.gz"
          tar -czvf "$TARBALL_NAME" wendy-cli-${{ matrix.platform }}/
          echo "tarball_name=$TARBALL_NAME" >> $GITHUB_OUTPUT
        id: create-tarball
      - name: Upload binary artifact
        id: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.create-tarball.outputs.tarball_name }}
          path: ${{ steps.create-tarball.outputs.tarball_name }}
          retention-days: 14
          if-no-files-found: error

  release:
    name: Release
    runs-on: ubuntu-22.04-arm
    needs: [determine-version, build]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
      - name: List files
        run: |
          ls -la
          # Create a newline-delimited list of tar.gz files
          {
            echo 'FILES<<EOF'
            find . -name "*.tar.gz" | sort
            echo 'EOF'
          } >> $GITHUB_ENV
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ needs.determine-version.outputs.version }}
          tag_name: ${{ needs.determine-version.outputs.version }}
          draft: false
          prerelease: true
          files: ${{ env.FILES }}
          generate_release_notes: true
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       # NEW: move/update a 'latest' tag to this prerelease's commit
      # needed so .git exists in the workspace
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # grab history + tags
      - name: Update 'latest' tag
        run: |
          set -euo pipefail
          git fetch origin --tags --force
          TAG='${{ needs.determine-version.outputs.version }}'   # your tag, e.g. 2025.09.16-224322
          TARGET_SHA="$(git rev-list -n 1 "refs/tags/$TAG" || true)"
          if [ -z "$TARGET_SHA" ]; then TARGET_SHA="$GITHUB_SHA"; fi
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git tag -fa latest "$TARGET_SHA" -m "Latest prerelease: $TAG"
          git push -f origin refs/tags/latest

      - name: Set up Homebrew
        run: |
          sudo apt-get install build-essential procps curl file git
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      # Bump the formula in homebrew-tap
      - name: Create GitHub App Token
        id: app-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.CLI_PUBLISHER_APP_ID }}
          private-key: ${{ secrets.CLI_PUBLISHER_APP_PRIVATE_KEY }}
          owner: wendylabsinc
          repositories: homebrew-tap
      - name: Bump formula in homebrew-tap
        uses: dawidd6/action-homebrew-bump-formula@v5
        with:
          token: ${{ steps.app-token.outputs.token }}
          tap: wendylabsinc/homebrew-tap
          formula: wendy
          tag: ${{ needs.determine-version.outputs.version }}
          revision: ${{ github.sha }}
          no_fork: true
          force: true
